### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by imSunnyk** [delitamakanda/my-elearning#25]
Hello,

What are the proper process to run your project... I'm interest to make a e learning portal....I want to try this out please....

**Comment by delitamakanda** [comment]
hi,

First, you need a virtual python environment 

Second you can follow theses steps:

```bash
# set an virtual env
virtualenv venv -p python3

source venv/bin/activate

pip install -r requirements-dev.txt

python3 manage.py migrate

python3 manage.py runserver
```

**Comment by imSunnyk** [comment]
Thank you very much

**Comment by imSunnyk** [comment]
while using python3 manage.py migrate..... I'm getting this issue so cuould u plz help
what to put in DEFAULT_FROM_EMAIL, DEVELOPER_KEY, CELERY_BROKER_URL and CELERY_RESULT_BACKEND

DEFAULT_FROM_EMAIL = config('ADMIN_EMAIL')

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Session
SESSION_EXPIRE_SECONDS = 18000  # 5 hours
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True

DEVELOPER_KEY = config('DEVELOPER_API_KEY')

# corsheaders
CORS_ORIGIN_ALLOW_ALL = False
CORS_ALLOW_CREDENTIALS = True

# Task async
CELERY_BROKER_URL = config('REDIS_URL')
CELERY_RESULT_BACKEND = config('REDIS_URL')

**Comment by delitamakanda** [comment]
DEVELOPER_API_KEY  for google apis youtube data api v3 https://console.developers.google.com/apis/library?folder=&organizationId=&project=artful-affinity-286613&q=you

CELERY_BROKER_URL for redis dev instance redis://127.0.0.1:6379/0

**Comment by imSunnyk** [comment]
Hi ,

I installed all dependencies , added developer key when I run command

Python manage.py migrate 

It's showing 
Modulenotfounderror: no module named 'termsandconditions'
